# Generated by Django 5.0.6 on 2024-06-30 21:20

import grapesjs_writer.assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_model_class', models.TextField(verbose_name='template model class')),
                ('image', models.ImageField(upload_to=grapesjs_writer.assets.models.upload_to_path, verbose_name='image')),
                ('display_name', models.CharField(blank=True, default='', max_length=150, verbose_name='display name')),
            ],
            options={
                'verbose_name': 'Asset item',
                'verbose_name_plural': 'Assets itens',
            },
        ),
    ]
