# Generated by Django 5.0.6 on 2024-06-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0002_emailtemplate_template_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_code',
            field=models.TextField(blank=True, default=dict, verbose_name='template code'),
        ),
    ]
