# Generated by Django 5.0.6 on 2024-06-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0003_alter_emailtemplate_template_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_code',
            field=models.TextField(blank=True, default='', verbose_name='template code'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_data',
            field=models.JSONField(default=dict, verbose_name='template data'),
        ),
    ]
